In [ ]:
# Question 1
# 1st question
import numpy as np
arr= np.random.randint(0,1,(2,2))
print(arr)

[[0 0]
 [0 0]]


In [ ]:
# 2nd question
import numpy as np
import random
arr= np.random.randint(1,2,(4,2))
print(arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# 3rd 4th and 5th question
import numpy as np
filled_array = np.full((3, 3),fill_value= 7)
print(filled_array)
ones_like = np.ones_like(filled_array)
print(ones_like)

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# 6th question
import numpy as np
new_list = [1,2,3,4]
new_array = np.array(new_list)
print(new_array)

[1 2 3 4]


In [ ]:
# Part 2
# Quetion 1
import numpy as np
array_10_to_49 = np.arange(10, 50)
print(array_10_to_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Part 2
# Ques 2
import numpy as np
array_0_8= np.reshape((np.arange(0,9)),(3,3))
print(array_0_8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Part 2
# Ques 3
import numpy as np
id_matrix = np.eye(3)
print(id_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Part 2
# Ques 4
import numpy as np
random_array = np.random.rand(30)
mean_arr = random_array.mean()
print(mean_arr)

0.4975296476439867


In [ ]:
# Part 2
# Ques 5
import numpy as np
array = np.random.randint(1,100,size=(10,10))
min_val = array.min()
max_val = array.max()
print("The random elements array is: ",array)
print("The min value of the matrix is:",min_val)
print("The max value of the matrix is:",max_val)

The random elements array is:  [[71 14 40 80 23 42 13 19 60 38]
 [71 30 76 89 43 17 80 26 88 54]
 [67 65  4 52 84 68  3 85 78 68]
 [20  4 80  4  3 81 86 80 41 20]
 [71 11 93 93 70 64 12 65  2 36]
 [94 74 16 99 75  2 67 85 95 27]
 [65 79 97 65 50 99 23 44 15 18]
 [69  4 45  9 88 19  7 76 24  8]
 [41 32  3 33 36 19 46 88 20 20]
 [ 9 78 39 73 88  3 95 86 74 91]]
The min value of the matrix is: 2
The max value of the matrix is: 99


In [ ]:
# Part 2
# Ques 6
import numpy as np
array = np.zeros((10,10))
print(array)
array[0][4]= 1
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Part 2
# Ques 7
import numpy as np
array = [1,2,0,0,4,0]
array.reverse()
# array.sort()
print(array)


[0, 4, 0, 0, 2, 1]


In [ ]:
# Part 2
# Ques 8
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
array[0,:]=1
array[-1,:] =1
array[:,0]=1
array[:,-1]=1
print(array)


[[1 1 1]
 [1 5 1]
 [1 1 1]]


In [ ]:
# Part 2
# Ques 9
import numpy as np
check = np.random.randint(0,1,(8,8))
check[1::2, ::2] = 1
check[::2, 1::2] = 1
print(check)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Part 3
# Ques 1
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result1 = x+y
result2 = np.add(x,y)
print(result1)
print(result2)

v = np.array([9,10])
w = np.array([11,12])
result1 = np.add(v,w)
print(result1)

[[ 6  8]
 [10 13]]
[[ 6  8]
 [10 13]]
[20 22]


In [ ]:
# Part 3
# Ques 2
import numpy as np
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result = np.subtract(x,y)
print(result)

v = np.array([9,10])
w = np.array([11,12])
result = np.subtract(v,w)
print(result)

[[-4 -4]
 [-4 -3]]
[-2 -2]


In [ ]:
# Part 3
# Ques 3
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

res1 = v*2
res2= w*3
res3 = x*4
res4=y*5

print(res1)
print(res2)
print(res3)
print(res4)

[18 20]
[33 36]
[[ 4  8]
 [12 20]]
[[25 30]
 [35 40]]


In [ ]:
# Part 3
# Ques 4
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

square1 = np.square(v)
square2 = np.square(w)
square3 = np.square(x)
square4 = np.square(y)
print(square1,"\n", square2,"\n", square3,"\n", square4)

[ 81 100] 
 [121 144] 
 [[ 1  4]
 [ 9 25]] 
 [[25 36]
 [49 64]]


In [ ]:
# Part 3
# Ques 5
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])

result1 = np.dot(v,w)
result2 = np.dot(x,v)
result3 =np.dot(x,y)

print(result1)
print(result2)
print(result3)

219
[29 77]
[[19 22]
 [50 58]]


In [ ]:
# Part 3
# Ques 6
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result1 = np.concatenate((v,w))
result2 = np.concatenate((x,y),axis = 1)
print(result1)
print(result2)
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

[ 9 10 11 12]
[[1 2 5 6]
 [3 5 7 8]]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Part 3
# Ques 7
import numpy as np
v = np.array([9,10])
w = np.array([11,12])
x = np.array([[1,2],
              [3,5]])
y = np.array([[5,6]
            , [7,8]])
result3 = np.concatenate((x,v))
print(result3)
# dimensional error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [ ]:
# Part 4
# QUes 1
    #  part 1
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv=np.linalg.inv(A)
result = np.dot(A_inv,A)
result = np.round(result, decimals=10)
I = np.eye(2,2)
# print(I)
if np.allclose(result,I) :
    print("Equal")
else:
    print("Not equal")

Equal


In [ ]:
# Part 4
#    part  2
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
res1 = np.matmul(A,B)
res2 = np.matmul(B,A)
if np.allclose(res1,res2):
    print("Equal")
else:
    print("Not equal")

Not equal


In [ ]:
  # Part 4
 # Part 3
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
res1 = np.matmul(A,B)
transpAB = np.transpose(res1)
transpA = np.transpose(A)
transpB = np.transpose(B)
res2 = np.matmul(transpB,transpA)
if np.allclose(transpAB,res2):
        print("Equal")
else:
        print("Not equal")

Equal


In [ ]:
# Part 4
# Ques 2 and 3
import numpy as np
A= ([[2,-3,1],
    [1,-1,2],
    [3,1,-1]])

B= ([-1],
    [-3],
    [9])

A_inv = np.linalg.inv(A)
res = np.dot(A_inv,B)
print("The solution is: ")
print(res)

The solution is: 
[[ 2.]
 [ 1.]
 [-2.]]
